name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - 'ChangeLog'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'ChangeLog'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # See https://github.com/purcell/nix-emacs-ci/blob/master/flake.nix
        emacs_version:
          - 29.2
          - 28.2
          - 27.2
          - 26.3
          - 25.3
          - 24.5
          - 24.4
          - snapshot
    env:
      coveralls_skip_versions: "" # Empty list
    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

    - name: Check out the source code
      uses: actions/checkout@v4

    - name: Install Elisp dependencies
      run: eldev prepare test

    - name: Compile the package
      run: eldev compile

    - name: Run the test suite
      run: |
        eldev -p -dtT test

    - name: Run the test suite with flx-ido
      run: |
        eldev -p -S '(load-file "./Eldev-flx-ido")' -dtT test

    - name: Run the test suite in source mode (for undercover)
      if: ${{ ! contains(env.coveralls_skip_versions, matrix.emacs_version) }}
      env:
        COVERALLS_FLAG_NAME: Emacs ${{ matrix.emacs_version }}
        COVERALLS_PARALLEL: 1
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        eldev -s -dtT test
        eldev -s -S '(load-file "./Eldev-flx-ido")' -dtT test

  finalize:
    runs-on: ubuntu-latest
    if: always()
    needs: test
    steps:
    - name: Finalize Coveralls
      run: |
        curl "https://coveralls.io/webhook?repo_name=$GITHUB_REPOSITORY&repo_token=${{ secrets.GITHUB_TOKEN }}" -d "payload[build_num]=$GITHUB_RUN_NUMBER&payload[status]=done"
